name: update-fasta-dbs

on:
  push:
  schedule:
    - cron: 30 12 * * *

jobs:
  update-dbs:
    runs-on: ubuntu-latest

      
    steps:       
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::shiny
            any::DT
            any::plotly
            any::dplyr
            any::Biostrings
            any::stringi
            any::stringr
            any::shinyalert
            any::shinybusy
            
      - name: Check out repository
        uses: actions/checkout@v4
            
      - name: Update Databases
        run: Rscript -e 'source("./scripts/update_databases.R")'

      - name: Commit files using git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./databases/ncbi_reference_table.Rds ./databases/uniprot_ids_reference_table.Rds
          git commit -m "automated monthly database update"
          git push origin
          
